const express = require('express')
const router = express.Router()
const adminController = require("../controllers/Admin.controller")
const otpController = require("../controllers/Otp.controller")
const {adminMiddleWare, authUserMiddleWare, productAgentMiddleWare} = require('../middleware/AuthMiddleWare')

router.post('/send-otp' ,  otpController.sendOtp)   
router.post('/verify-otp' ,  otpController.verifyOtp) 
router.post('/sign-in', adminController.signIn)
router.post('/create-staff', adminMiddleWare, adminController.createStaff)
router.post('/create-admin', adminMiddleWare, adminController.createAdmin)
router.post('/forget-password', adminController.forgetPassword)
router.put('/change-password/:id', authUserMiddleWare, adminController.changePassword)
router.put('/update-admin/:id', authUserMiddleWare, adminController.updateAdmin)
router.get('/get-all-users', productAgentMiddleWare, adminController.getAllUser)
router.get('/get-all-staffs', adminMiddleWare, adminController.getAllStaff)
router.get('/get-detail-staff/:id', authUserMiddleWare, adminController.getDetailStaff)
router.get('/get-detail-admin/:id', authUserMiddleWare, adminController.getDetailAdmin)
router.put('/update-role-staff/:id', adminMiddleWare, adminController.updateRoleStaff)
router.get('/get-revenue', adminController.getRevenue)
module.exports = router