const express = require('express')
const router = express.Router()
const userController = require("../controllers/User.controller")
const otpController = require("../controllers/Otp.controller")
const notificationController = require("../controllers/Notification.controller")
const {authUserMiddleWare} = require('../middleware/AuthMiddleWare')

router.post('/send-otp' ,  otpController.sendOtp)   
router.post('/verify-otp' ,  otpController.verifyOtp) 
router.post('/signUpPhone', userController.signUpPhone)
router.post('/signUpEmail', userController.signUpEmail)
router.post('/sign-in-google', userController.signInGoogle)
router.post('/signIn', userController.signIn)
router.get('/getUser/:id', authUserMiddleWare, userController.getDetailUser)
router.patch('/edit-user/:id', authUserMiddleWare, userController.editUser)
router.post('/check-current-password/:id', authUserMiddleWare, userController.checkCurrentPass)
router.put('/change-password/:id', authUserMiddleWare, userController.changePassword)
router.post('/forget-password', userController.forgetPassword)
router.delete('/delete-user/:id', authUserMiddleWare, userController.deleteUser)
router.post('/add-address/:id', authUserMiddleWare, userController.addAddress)
router.put('/:id/address/:addressId', authUserMiddleWare, userController.updateAddress);
router.delete('/:id/delete-address/:addressId', authUserMiddleWare, userController.deleteAddress);
router.put('/:id/set-address-default/:address_id', authUserMiddleWare, userController.setAddressDefault)
router.post('/sign-out' ,  userController.signOut)  
router.post('/refresh-token' ,  userController.refreshToken) 
router.get('/notification/:id', authUserMiddleWare, notificationController.getAllNotify)
module.exports = router